## imports

In [3]:
import pandas as pd
from datasets import load_dataset

In [4]:
smartdata = load_dataset('smartdata')

Reusing dataset smartdata (/Users/elisabeth/.cache/huggingface/datasets/smartdata/smartdata-v3_20200302/1.1.0/9a495ae1310b73f664fa8644c7472f87ec728326e37fe67e030107712b81167f)

  0%|          | 0/3 [00:00<?, ?it/s]

In [5]:
smartdata

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 1861
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 230
    })
    validation: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 228
    })
})

In [13]:
smartdata['train']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 1861
})

In [9]:
smartdata['test']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 230
})

In [11]:
smartdata['validation']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 228
})

In [68]:
train_ds[0]

{'id': '671734738147758080',
 'tokens': ['A1',
  'Zwischen',
  'AS',
  'Munsbach',
  'und',
  'AS',
  'Flaxweiler',
  'Bauarbeiten',
  ',',
  'rechter',
  'Fahrstreifen',
  'gesperrt',
  ',',
  'Verkehrsbehinderung',
  ',',
  'Dauer',
  ':',
  '02.12.2015',
  '...',
  '#ACL_A1'],
 'ner_tags': [17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 1, 0, 17]}

In [69]:
train_ds.column_names

['id', 'tokens', 'ner_tags']

In [70]:
features = train_ds.features

In [71]:
train_ds.features['ner_tags']

Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)

In [72]:
ner_tags = train_ds.features['ner_tags']

In [73]:
ner_tags?

Type:        Sequence
String form: Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I <...> PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)
File:        ~/repos/NER-german-telegram/venv/lib/python3.9/site-packages/datasets/features/features.py
Docstring:
Construct a list of feature from a single type or a dict of types.
Mostly here for compatiblity with tfds.

Args:
    feature: A list of features of a single type or a dictionary of types.
    length (`int`): Length of the sequence.

Example:

```py
>>> from datasets import Features, Sequence, Value, ClassLabel
>>> features = Features({'post': Sequence(feature={'text': Value(dtype='string'), 'upvotes': Value(dtype='int32'), 'label': ClassLabel(num_classes=2, names=['hot', 'cold'])})})
>>> features
{'post': Sequence(feature={'text': Value(dtype='string', id=None), 'upvotes': Value(dtype='int32', id=None), 'label': ClassLabel(num_classes=2, names=['hot', 'cold'], id=None)}, length=-1, id=None)}
```

In [74]:
ner_tags.length

-1

In [75]:
# smartdata.set_format(type='pandas')

In [76]:
# df = smartdata['train'][:]

In [77]:
# df.head()

In [78]:
# def label_int2str(row):
  #  return smartdata['train'].features['ner_tags'].int2str(row)

In [79]:
# df['label_names'] = df['ner_tags'].apply(label_int2str)

In [80]:
for key, value in smartdata["train"].features.items():
    print(f"{key}: {value}")

id: Value(dtype='string', id=None)
tokens: Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)
ner_tags: Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)

In [81]:
tags = smartdata["train"].features["ner_tags"].feature
print(tags)

ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None)

In [82]:
def create_tag_names(batch):
    return {"ner_tags_str": [tags.int2str(idx) for idx in batch["ner_tags"]]}

In [83]:
smartdata = smartdata.map(create_tag_names)

  0%|          | 0/1861 [00:00<?, ?ex/s]

  0%|          | 0/230 [00:00<?, ?ex/s]

  0%|          | 0/228 [00:00<?, ?ex/s]

In [84]:
smartdata

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 1861
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 230
    })
    validation: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 228
    })
})

In [85]:
smartdata["train"][0]

{'id': '671734738147758080',
 'tokens': ['A1',
  'Zwischen',
  'AS',
  'Munsbach',
  'und',
  'AS',
  'Flaxweiler',
  'Bauarbeiten',
  ',',
  'rechter',
  'Fahrstreifen',
  'gesperrt',
  ',',
  'Verkehrsbehinderung',
  ',',
  'Dauer',
  ':',
  '02.12.2015',
  '...',
  '#ACL_A1'],
 'ner_tags': [17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 1, 0, 17],
 'ner_tags_str': ['B-LOCATION_STREET',
  'O',
  'B-LOCATION',
  'I-LOCATION',
  'O',
  'B-LOCATION',
  'I-LOCATION',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-TRIGGER',
  'O',
  'O',
  'O',
  'B-DATE',
  'O',
  'B-LOCATION_STREET']}

In [86]:
example = smartdata["train"][0]
pd.DataFrame([example["tokens"], example["ner_tags_str"]],
['Tokens', 'Tags'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
Tokens,A1,Zwischen,AS,Munsbach,und,AS,Flaxweiler,Bauarbeiten,",",rechter,Fahrstreifen,gesperrt,",",Verkehrsbehinderung,",",Dauer,:,02.12.2015,...,#ACL_A1
Tags,B-LOCATION_STREET,O,B-LOCATION,I-LOCATION,O,B-LOCATION,I-LOCATION,O,O,O,O,O,O,B-TRIGGER,O,O,O,B-DATE,O,B-LOCATION_STREET

In [59]:
# smartdata.set_format(type='pandas')

In [90]:
from collections import defaultdict

from collections import Counter

split2freqs = defaultdict(Counter)
for split, dataset in smartdata.items():
    for row in dataset["ner_tags_str"]:
        for tag in row:
            if tag.startswith("B"):
                tag_type = tag.split("-")[1]
                split2freqs[split][tag_type] += 1
pd.DataFrame.from_dict(split2freqs, orient="index")

,LOCATION_STREET,LOCATION,TRIGGER,DATE,LOCATION_CITY,TIME,ORGANIZATION_COMPANY,PERSON,NUMBER,ORGANIZATION,LOCATION_ROUTE,LOCATION_STOP,DURATION,DISASTER_TYPE,DISTANCE,ORG_POSITION
train,567,2249,1061,1511,1922,556,2384,978,1519,839,275,788,297,179,168,85
test,80,240,151,168,218,69,236,100,167,71,46,143,43,14,19,9
validation,64,298,127,167,252,69,311,127,156,76,37,74,49,31,17,12

In [60]:
df = smartdata['train'][:]

In [61]:
df.head()

,id,tokens,ner_tags,ner_tags_str
0,671734738147758080,"[A1, Zwischen, AS, Munsbach, und, AS, Flaxweil...","[17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31,...","[[B-LOCATION_STREET, O, B-LOCATION, I-LOCATION..."
1,744611433661472768,"[RT, @broeselbub, :, Wer, diesen, #EM16, -, Sp...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O,..."
2,http://www.viz-info.de/LMS-BR_r_LMS-BR_63500@2...,"[Sonstiges, Abschnitt, :, (, Berlin, ), Gültig...","[0, 0, 0, 0, 11, 0, 0, 0, 0, 1, 29, 0, 0, 0, 0...","[[O, O, O, O, B-LOCATION_CITY, O, O, O, O, B-D..."
3,http://www.ndr.de/nachrichten/verkehr/index.ht...,"[Vorsicht, bitte, in, beiden, Richtungen, auf,...","[0, 0, 0, 9, 10, 0, 0, 17, 11, 0, 11, 0, 9, 10...","[[O, O, O, B-LOCATION, I-LOCATION, O, O, B-LOC..."
4,699639035099279361,"[RT, @BILD, :, Wegen, Schulden, :, Rapper, #Ka...","[0, 23, 0, 0, 0, 0, 0, 27, 0, 23, 0, 0, 27, 28...","[[O, B-ORGANIZATION_COMPANY, O, O, O, O, O, B-..."