## imports

In [1]:
import pandas as pd
from datasets import load_dataset

In [7]:
ds = load_dataset('germeval_14', ignore_verifications=True)

Downloading and preparing dataset germeval_14/germeval_14 (download: 9.81 MiB, generated: 17.19 MiB, post-processed: Unknown size, total: 27.00 MiB) to /Users/elisabeth/.cache/huggingface/datasets/germeval_14/germeval_14/2.0.0/0f174b84866aa3b8ebae65c271610520be4422405d7e8467bd24cfd493d325f0...

Downloading data files:   0%|          | 0/3 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/24000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2200 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5100 [00:00<?, ? examples/s]

Dataset germeval_14 downloaded and prepared to /Users/elisabeth/.cache/huggingface/datasets/germeval_14/germeval_14/2.0.0/0f174b84866aa3b8ebae65c271610520be4422405d7e8467bd24cfd493d325f0. Subsequent calls will reuse this data.

  0%|          | 0/3 [00:00<?, ?it/s]

In [8]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
        num_rows: 24000
    })
    validation: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
        num_rows: 2200
    })
    test: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
        num_rows: 5100
    })
})

In [9]:
ds['train']

Dataset({
    features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
    num_rows: 24000
})

In [10]:
ds['test']

Dataset({
    features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
    num_rows: 5100
})

In [11]:
ds['validation']

Dataset({
    features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags'],
    num_rows: 2200
})

In [14]:
train_ds = ds['train']
train_ds[0]

{'id': '0',
 'source': 'n-tv.de vom 26.02.2005 [2005-02-26] ',
 'tokens': ['Schartau',
  'sagte',
  'dem',
  '"',
  'Tagesspiegel',
  '"',
  'vom',
  'Freitag',
  ',',
  'Fischer',
  'sei',
  '"',
  'in',
  'einer',
  'Weise',
  'aufgetreten',
  ',',
  'die',
  'alles',
  'andere',
  'als',
  'überzeugend',
  'war',
  '"',
  '.'],
 'ner_tags': [19,
  0,
  0,
  0,
  7,
  0,
  0,
  0,
  0,
  19,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'nested_ner_tags': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [15]:
train_ds.column_names

['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags']

In [16]:
features = train_ds.features

In [17]:
train_ds.features['ner_tags']

Sequence(feature=ClassLabel(num_classes=25, names=['O', 'B-LOC', 'I-LOC', 'B-LOCderiv', 'I-LOCderiv', 'B-LOCpart', 'I-LOCpart', 'B-ORG', 'I-ORG', 'B-ORGderiv', 'I-ORGderiv', 'B-ORGpart', 'I-ORGpart', 'B-OTH', 'I-OTH', 'B-OTHderiv', 'I-OTHderiv', 'B-OTHpart', 'I-OTHpart', 'B-PER', 'I-PER', 'B-PERderiv', 'I-PERderiv', 'B-PERpart', 'I-PERpart'], id=None), length=-1, id=None)

In [18]:
train_ds.features['nested_ner_tags']

Sequence(feature=ClassLabel(num_classes=25, names=['O', 'B-LOC', 'I-LOC', 'B-LOCderiv', 'I-LOCderiv', 'B-LOCpart', 'I-LOCpart', 'B-ORG', 'I-ORG', 'B-ORGderiv', 'I-ORGderiv', 'B-ORGpart', 'I-ORGpart', 'B-OTH', 'I-OTH', 'B-OTHderiv', 'I-OTHderiv', 'B-OTHpart', 'I-OTHpart', 'B-PER', 'I-PER', 'B-PERderiv', 'I-PERderiv', 'B-PERpart', 'I-PERpart'], id=None), length=-1, id=None)

In [75]:
# smartdata.set_format(type='pandas')

In [76]:
# df = smartdata['train'][:]

In [77]:
# df.head()

In [78]:
# def label_int2str(row):
  #  return smartdata['train'].features['ner_tags'].int2str(row)

In [79]:
# df['label_names'] = df['ner_tags'].apply(label_int2str)

In [19]:
for key, value in ds["train"].features.items():
    print(f"{key}: {value}")

id: Value(dtype='string', id=None)
source: Value(dtype='string', id=None)
tokens: Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)
ner_tags: Sequence(feature=ClassLabel(num_classes=25, names=['O', 'B-LOC', 'I-LOC', 'B-LOCderiv', 'I-LOCderiv', 'B-LOCpart', 'I-LOCpart', 'B-ORG', 'I-ORG', 'B-ORGderiv', 'I-ORGderiv', 'B-ORGpart', 'I-ORGpart', 'B-OTH', 'I-OTH', 'B-OTHderiv', 'I-OTHderiv', 'B-OTHpart', 'I-OTHpart', 'B-PER', 'I-PER', 'B-PERderiv', 'I-PERderiv', 'B-PERpart', 'I-PERpart'], id=None), length=-1, id=None)
nested_ner_tags: Sequence(feature=ClassLabel(num_classes=25, names=['O', 'B-LOC', 'I-LOC', 'B-LOCderiv', 'I-LOCderiv', 'B-LOCpart', 'I-LOCpart', 'B-ORG', 'I-ORG', 'B-ORGderiv', 'I-ORGderiv', 'B-ORGpart', 'I-ORGpart', 'B-OTH', 'I-OTH', 'B-OTHderiv', 'I-OTHderiv', 'B-OTHpart', 'I-OTHpart', 'B-PER', 'I-PER', 'B-PERderiv', 'I-PERderiv', 'B-PERpart', 'I-PERpart'], id=None), length=-1, id=None)

In [20]:
tags = ds["train"].features["ner_tags"].feature
print(tags)

ClassLabel(num_classes=25, names=['O', 'B-LOC', 'I-LOC', 'B-LOCderiv', 'I-LOCderiv', 'B-LOCpart', 'I-LOCpart', 'B-ORG', 'I-ORG', 'B-ORGderiv', 'I-ORGderiv', 'B-ORGpart', 'I-ORGpart', 'B-OTH', 'I-OTH', 'B-OTHderiv', 'I-OTHderiv', 'B-OTHpart', 'I-OTHpart', 'B-PER', 'I-PER', 'B-PERderiv', 'I-PERderiv', 'B-PERpart', 'I-PERpart'], id=None)

In [21]:
def create_tag_names(batch):
    return {"ner_tags_str": [tags.int2str(idx) for idx in batch["ner_tags"]]}

In [22]:
ds = ds.map(create_tag_names)

Parameter 'function'=<function create_tag_names at 0x7fda6ace20d0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

  0%|          | 0/24000 [00:00<?, ?ex/s]

  0%|          | 0/2200 [00:00<?, ?ex/s]

  0%|          | 0/5100 [00:00<?, ?ex/s]

In [23]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags', 'ner_tags_str'],
        num_rows: 24000
    })
    validation: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags', 'ner_tags_str'],
        num_rows: 2200
    })
    test: Dataset({
        features: ['id', 'source', 'tokens', 'ner_tags', 'nested_ner_tags', 'ner_tags_str'],
        num_rows: 5100
    })
})

In [24]:
ds["train"][0]

{'id': '0',
 'source': 'n-tv.de vom 26.02.2005 [2005-02-26] ',
 'tokens': ['Schartau',
  'sagte',
  'dem',
  '"',
  'Tagesspiegel',
  '"',
  'vom',
  'Freitag',
  ',',
  'Fischer',
  'sei',
  '"',
  'in',
  'einer',
  'Weise',
  'aufgetreten',
  ',',
  'die',
  'alles',
  'andere',
  'als',
  'überzeugend',
  'war',
  '"',
  '.'],
 'ner_tags': [19,
  0,
  0,
  0,
  7,
  0,
  0,
  0,
  0,
  19,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'nested_ner_tags': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'ner_tags_str': ['B-PER',
  'O',
  'O',
  'O',
  'B-ORG',
  'O',
  'O',
  'O',
  'O',
  'B-PER',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O']}

In [29]:
example = ds["train"][3]
pd.DataFrame([example["tokens"], example["ner_tags_str"]],
['Tokens', 'Tags']).transpose()

                   Tokens        Tags
0                  Bayern       B-ORG
1                 München       I-ORG
2                     ist           O
3                  wieder           O
4              alleiniger           O
5                    Top-           O
6                 Favorit           O
7                     auf           O
8                     den           O
9                  Gewinn           O
10                    der           O
11              deutschen  B-LOCderiv
12  Fußball-Meisterschaft           O
13                      .           O

In [59]:
# smartdata.set_format(type='pandas')

In [90]:
from collections import defaultdict

from collections import Counter

split2freqs = defaultdict(Counter)
for split, dataset in smartdata.items():
    for row in dataset["ner_tags_str"]:
        for tag in row:
            if tag.startswith("B"):
                tag_type = tag.split("-")[1]
                split2freqs[split][tag_type] += 1
pd.DataFrame.from_dict(split2freqs, orient="index")

,LOCATION_STREET,LOCATION,TRIGGER,DATE,LOCATION_CITY,TIME,ORGANIZATION_COMPANY,PERSON,NUMBER,ORGANIZATION,LOCATION_ROUTE,LOCATION_STOP,DURATION,DISASTER_TYPE,DISTANCE,ORG_POSITION
train,567,2249,1061,1511,1922,556,2384,978,1519,839,275,788,297,179,168,85
test,80,240,151,168,218,69,236,100,167,71,46,143,43,14,19,9
validation,64,298,127,167,252,69,311,127,156,76,37,74,49,31,17,12

In [60]:
df = smartdata['train'][:]

In [61]:
df.head()

,id,tokens,ner_tags,ner_tags_str
0,671734738147758080,"[A1, Zwischen, AS, Munsbach, und, AS, Flaxweil...","[17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31,...","[[B-LOCATION_STREET, O, B-LOCATION, I-LOCATION..."
1,744611433661472768,"[RT, @broeselbub, :, Wer, diesen, #EM16, -, Sp...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O,..."
2,http://www.viz-info.de/LMS-BR_r_LMS-BR_63500@2...,"[Sonstiges, Abschnitt, :, (, Berlin, ), Gültig...","[0, 0, 0, 0, 11, 0, 0, 0, 0, 1, 29, 0, 0, 0, 0...","[[O, O, O, O, B-LOCATION_CITY, O, O, O, O, B-D..."
3,http://www.ndr.de/nachrichten/verkehr/index.ht...,"[Vorsicht, bitte, in, beiden, Richtungen, auf,...","[0, 0, 0, 9, 10, 0, 0, 17, 11, 0, 11, 0, 9, 10...","[[O, O, O, B-LOCATION, I-LOCATION, O, O, B-LOC..."
4,699639035099279361,"[RT, @BILD, :, Wegen, Schulden, :, Rapper, #Ka...","[0, 23, 0, 0, 0, 0, 0, 27, 0, 23, 0, 0, 27, 28...","[[O, B-ORGANIZATION_COMPANY, O, O, O, O, O, B-..."