# Prepare data

In [155]:
from glob import glob
import pandas as pd

In [156]:
# Pfad so anpassen, dass dort passende Dateien zum EInlesen liegen
files = glob("data/telegram/*.json")
files

['data/telegram/tg_01.json',
 'data/telegram/project_3_final.json',
 'data/telegram/project_1_final.json',
 'data/telegram/tg_04.json',
 'data/telegram/project_7_final.json',
 'data/telegram/tg_05.json',
 'data/telegram/tg_02.json',
 'data/telegram/project_5_final.json']

In [157]:
data = []
for f in files:
    data.append(pd.read_json(f))
df = pd.concat(data)

In [158]:
len(df)

3427

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3427 entries, 0 to 999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3427 non-null   int64
 1   annotations  3427 non-null   object
 2   file_upload  3427 non-null   object
 3   drafts       3427 non-null   object
 4   predictions  3427 non-null   object
 5   data         3427 non-null   object
 6   meta         3427 non-null   object
 7   created_at   3427 non-null   datetime64[ns, UTC]
 8   updated_at   3427 non-null   datetime64[ns, UTC]
 9   project      3427 non-null   int64
dtypes: datetime64[ns, UTC](2), int64(2), object(6)
memory usage: 294.5+ KB

In [160]:
df.head()

,id,annotations,file_upload,drafts,predictions,data,meta,created_at,updated_at,project
0,15832,"[{'id': 4919, 'completed_by': 4, 'result': [{'...",bb2f993d-whoa_tel_g1.csv,[],[],"{'Unnamed: 0': 17, 'channel_name': 'mh171702Q2...",{},2022-04-12 16:52:06.115346+00:00,2022-04-14 19:18:55.106629+00:00,28
1,16102,"[{'id': 4913, 'completed_by': 4, 'result': [{'...",bb2f993d-whoa_tel_g1.csv,[],[],"{'Unnamed: 0': 287, 'channel_name': 'ATTILAHIL...",{},2022-04-12 16:52:06.138724+00:00,2022-04-14 19:15:54.059878+00:00,28
2,15867,"[{'id': 4424, 'completed_by': 4, 'result': [{'...",bb2f993d-whoa_tel_g1.csv,[],[],"{'Unnamed: 0': 52, 'channel_name': 'TalaWolf',...",{},2022-04-12 16:52:06.117431+00:00,2022-04-12 18:05:58.854436+00:00,28
3,16314,"[{'id': 4912, 'completed_by': 4, 'result': [{'...",bb2f993d-whoa_tel_g1.csv,[],[],"{'Unnamed: 0': 499, 'channel_name': 'derdeutsc...",{},2022-04-12 16:52:06.156720+00:00,2022-04-12 16:52:06.156732+00:00,28
4,16313,"[{'id': 4951, 'completed_by': 4, 'result': [{'...",bb2f993d-whoa_tel_g1.csv,[],[],"{'Unnamed: 0': 498, 'channel_name': 'impfenmus...",{},2022-04-12 16:52:06.156652+00:00,2022-04-12 16:52:06.156663+00:00,28

In [161]:
df.tail()

,id,annotations,file_upload,drafts,predictions,data,meta,created_at,updated_at,project
995,11820,"[{'id': 3423, 'completed_by': 4, 'result': [{'...",c9544221-tel_lab_update_P5.csv,[],[],"{'Unnamed: 0': 2048, 'channel_name': 'mzwnews'...",{},2022-02-17 16:19:32.529127+00:00,2022-02-17 16:19:32.529138+00:00,24
996,11818,"[{'id': 3393, 'completed_by': 4, 'result': [{'...",c9544221-tel_lab_update_P5.csv,[],[],"{'Unnamed: 0': 2691, 'channel_name': 'stefanma...",{},2022-02-17 16:19:32.529020+00:00,2022-02-17 16:19:32.529031+00:00,24
997,11817,"[{'id': 2266, 'completed_by': 4, 'result': [{'...",c9544221-tel_lab_update_P5.csv,[],[],"{'Unnamed: 0': 2449, 'channel_name': 'hagengre...",{},2022-02-17 16:19:32.528967+00:00,2022-02-17 16:19:32.528980+00:00,24
998,11816,"[{'id': 3765, 'completed_by': 4, 'result': [{'...",c9544221-tel_lab_update_P5.csv,[],[],"{'Unnamed: 0': 1396, 'channel_name': 'dsindf',...",{},2022-02-17 16:19:32.528911+00:00,2022-02-17 16:19:32.528922+00:00,24
999,11815,"[{'id': 3371, 'completed_by': 4, 'result': [{'...",c9544221-tel_lab_update_P5.csv,[],[],"{'Unnamed: 0': 198, 'channel_name': 'ATTILAHIL...",{},2022-02-17 16:19:32.528838+00:00,2022-02-17 16:19:32.528868+00:00,24

## reduce to necessary columns

In [162]:
data = df[['id', 'annotations', 'data']]

In [163]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3427 entries, 0 to 999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3427 non-null   int64
 1   annotations  3427 non-null   object
 2   data         3427 non-null   object
dtypes: int64(1), object(2)
memory usage: 107.1+ KB

In [164]:
data.columns

Index(['id', 'annotations', 'data'], dtype='object')

## explode nested columns, extract result values from annotations

In [165]:
data = data.explode('annotations', 'data')

In [166]:
data.columns

Index(['id', 'annotations', 'data'], dtype='object')

In [167]:
data['annotation_results'] = data.annotations.apply(lambda x: x['result'])

In [168]:
data.columns

Index(['id', 'annotations', 'data', 'annotation_results'], dtype='object')

## extract annotation results for all categories

In [169]:
categories = ['conspiracy', 
              'antisemitism', 
              'conspiracy_stance', 
              'conspiracy_sub', 
              'antisemitism_sub', 
              'antisemitism_stance', 
              'others', 
              'technical']

In [170]:
def extract_annotation_results_per_category(row, category):
    for i in range(len(row)):
        if row[i]['from_name'] == category:
            labels = row[i]['value']['choices']
            return ", ".join(labels)

In [171]:
def extract_annotation_results(df, categories):
    res = df.copy()
    
    for category in categories:
        res[category] = res['annotation_results'].apply(lambda x: extract_annotation_results_per_category(x, category=category) if len(x)> 0 else None)
    
    return res

In [172]:
data = extract_annotation_results(data, categories)

In [173]:
data.columns

Index(['id', 'annotations', 'data', 'annotation_results', 'conspiracy',
       'antisemitism', 'conspiracy_stance', 'conspiracy_sub',
       'antisemitism_sub', 'antisemitism_stance', 'others', 'technical'],
      dtype='object')

## extract annotations for 'others', 'technical'

In [174]:
data[['pandemic', 'gdr', 'memorize', 'unsuitable']] = None

In [175]:
data['pandemic'] = data['others'].map({'Pandemic Reference': True, 'Pandemic Reference, GDR Reference': True})

In [176]:
data['gdr'] = data['others'].map({'GDR Reference': True, 'Pandemic Reference, GDR Reference': True})

In [177]:
data['memorize'] = data['technical'].map({'Memorize Task': True})

In [178]:
data['unsuitable'] = data['technical'].map({'Task unsuitable': True, 'Memorize Task, Task unsuitable': True})

In [179]:
data.columns

Index(['id', 'annotations', 'data', 'annotation_results', 'conspiracy',
       'antisemitism', 'conspiracy_stance', 'conspiracy_sub',
       'antisemitism_sub', 'antisemitism_stance', 'others', 'technical',
       'pandemic', 'gdr', 'memorize', 'unsuitable'],
      dtype='object')

In [180]:
# data.to_csv('test.csv')

In [181]:
# data.data.values

## extract text values

In [182]:
data.columns

Index(['id', 'annotations', 'data', 'annotation_results', 'conspiracy',
       'antisemitism', 'conspiracy_stance', 'conspiracy_sub',
       'antisemitism_sub', 'antisemitism_stance', 'others', 'technical',
       'pandemic', 'gdr', 'memorize', 'unsuitable'],
      dtype='object')

In [183]:
data['text'] = None

In [184]:
data.columns

Index(['id', 'annotations', 'data', 'annotation_results', 'conspiracy',
       'antisemitism', 'conspiracy_stance', 'conspiracy_sub',
       'antisemitism_sub', 'antisemitism_stance', 'others', 'technical',
       'pandemic', 'gdr', 'memorize', 'unsuitable', 'text'],
      dtype='object')

In [185]:
data['text'] = data['data'].apply(lambda x: x['text'] if len(x)> 0 else None)

In [186]:
data.head()

,id,annotations,data,annotation_results,conspiracy,antisemitism,conspiracy_stance,conspiracy_sub,antisemitism_sub,antisemitism_stance,others,technical,pandemic,gdr,memorize,unsuitable,text
0,15832,"{'id': 4919, 'completed_by': 4, 'result': [{'v...","{'Unnamed: 0': 17, 'channel_name': 'mh171702Q2...","[{'value': {'choices': ['Yes']}, 'id': 'keT0bk...",Yes,Yes,Belief,"Actor, Strategy, Reference",Other,Affirmative,Pandemic Reference,None,True,NaN,NaN,NaN,"Noch vor wenigen Wochen wurden ""Verschwörungst..."
1,16102,"{'id': 4913, 'completed_by': 4, 'result': [{'v...","{'Unnamed: 0': 287, 'channel_name': 'ATTILAHIL...","[{'value': {'choices': ['Yes']}, 'id': '86fxPg...",Yes,Yes,Belief,"Actor, Strategy, Goal, Reference",Other,Affirmative,None,None,NaN,NaN,NaN,NaN,BUNDESKANZLER UND BAUMEISTER YEHUDA TEICHTAL B...
2,15867,"{'id': 4424, 'completed_by': 4, 'result': [{'v...","{'Unnamed: 0': 52, 'channel_name': 'TalaWolf',...","[{'value': {'choices': ['Yes']}, 'id': '6u0Nb7...",Uncertain,Yes,None,None,Post-Holocaust,Affirmative,Pandemic Reference,None,True,NaN,NaN,NaN,"🔴 Impfstoff 'Holocaust' beginnt in Israel, als..."
3,16314,"{'id': 4912, 'completed_by': 4, 'result': [{'v...","{'Unnamed: 0': 499, 'channel_name': 'derdeutsc...","[{'value': {'choices': ['No']}, 'id': 'MASN9x5...",No,No,None,None,None,None,None,None,NaN,NaN,NaN,NaN,Seit Marionette Biden im Amt ist zeigt die isr...
4,16313,"{'id': 4951, 'completed_by': 4, 'result': [{'v...","{'Unnamed: 0': 498, 'channel_name': 'impfenmus...","[{'value': {'choices': ['No']}, 'id': '4zMfklB...",No,No,None,None,None,None,Pandemic Reference,None,True,NaN,NaN,NaN,In Israel sind nach Impfungen mit dem Mittel v...

## remove unsuitable tasks

In [187]:
data_clean = data[data['unsuitable'] != True]

In [188]:
len(data_clean)

3259

## adjust column order, reduce to necessary columns

In [189]:
data_clean = data_clean[['id', 
                         'conspiracy', 
                         'conspiracy_sub', 
                         'conspiracy_stance', 
                         'antisemitism', 
                         'antisemitism_sub', 
                         'antisemitism_stance',
                         'pandemic',
                         'gdr',
                         'memorize',
                         'unsuitable',
                         'text']]

## clean text

In [190]:
from unicodedata import normalize
import spacy
nlp = spacy.load("de_core_news_md")

In [191]:
def is_ascii(s):
    """Check if the characters in string s are in ASCII, U+0-U+7F."""
    return len(s) == len(s.encode())

In [192]:
def normalize_string_keep_umlauts(string_lowercase, umlauts = ['ä', 'ö', 'ü', 'ß']):
    """Normalize unicode strings, e.g. with special formatting, but keep umlauts"""
    out = []
    
    for c in string_lowercase: 
        if c in umlauts: 
            pass
        else: 
            c = normalize('NFKD', c)
            
        out.append(c)       
    return "".join([c for c in out])

## Questions: 
- only alphabetic tokens ok?
- remove stopwwords 'user', 'url' here or simply remove them from results?

In [1]:
def preprocess_text(s, output_col):

    s = s.replace('\n', ' ').lower()

    # only normalize strings which are not already in ascii-format
    if not is_ascii(s):
        s = normalize_string_keep_umlauts(s)
        
    doc = nlp(s)
    if output_col == 'tokens':
        words = [token.text for token in doc if token.is_alpha]
    
    else:
        words = [token.text for token in doc]
        
    return " ".join(words)

In [ ]:
df

In [194]:
data_clean['tokens'] = data_clean['text'].apply(lambda x: preprocess_text(x, output_col = 'tokens') if len(x)> 0 else None)

In [195]:
data_clean['clean_text'] = data_clean['text'].apply(lambda x: preprocess_text(x, output_col = 'clean_text') if len(x)> 0 else None)

In [196]:
data_clean.head()

,id,conspiracy,conspiracy_sub,conspiracy_stance,antisemitism,antisemitism_sub,antisemitism_stance,pandemic,gdr,memorize,unsuitable,text,tokens,clean_text
0,15832,Yes,"Actor, Strategy, Reference",Belief,Yes,Other,Affirmative,True,NaN,NaN,NaN,"Noch vor wenigen Wochen wurden ""Verschwörungst...",noch vor wenigen wochen wurden verschwörungsth...,"noch vor wenigen wochen wurden "" verschwörungs..."
1,16102,Yes,"Actor, Strategy, Goal, Reference",Belief,Yes,Other,Affirmative,NaN,NaN,NaN,NaN,BUNDESKANZLER UND BAUMEISTER YEHUDA TEICHTAL B...,bundeskanzler und baumeister yehuda teichtal b...,bundeskanzler und baumeister yehuda teichtal b...
2,15867,Uncertain,None,None,Yes,Post-Holocaust,Affirmative,True,NaN,NaN,NaN,"🔴 Impfstoff 'Holocaust' beginnt in Israel, als...",impfstoff holocaust beginnt in israel als der ...,"🔴 impfstoff ' holocaust ' beginnt in israel , ..."
3,16314,No,None,None,No,None,None,NaN,NaN,NaN,NaN,Seit Marionette Biden im Amt ist zeigt die isr...,seit marionette biden im amt ist zeigt die isr...,seit marionette biden im amt ist zeigt die isr...
4,16313,No,None,None,No,None,None,True,NaN,NaN,NaN,In Israel sind nach Impfungen mit dem Mittel v...,in israel sind nach impfungen mit dem mittel v...,in israel sind nach impfungen mit dem mittel v...

In [197]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3259 entries, 0 to 3426
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3259 non-null   int64
 1   conspiracy           3259 non-null   object
 2   conspiracy_sub       1077 non-null   object
 3   conspiracy_stance    1077 non-null   object
 4   antisemitism         3259 non-null   object
 5   antisemitism_sub     462 non-null    object
 6   antisemitism_stance  462 non-null    object
 7   pandemic             1502 non-null   object
 8   gdr                  25 non-null     object
 9   memorize             97 non-null     object
 10  unsuitable           0 non-null      object
 11  text                 3259 non-null   object
 12  tokens               3259 non-null   object
 13  clean_text           3259 non-null   object
dtypes: int64(1), object(13)
memory usage: 381.9+ KB

In [198]:
data_clean['platform'] = None

In [199]:
data_clean['platform'] = 'telegram'

In [200]:
data_clean.head()

,id,conspiracy,conspiracy_sub,conspiracy_stance,antisemitism,antisemitism_sub,antisemitism_stance,pandemic,gdr,memorize,unsuitable,text,tokens,clean_text,platform
0,15832,Yes,"Actor, Strategy, Reference",Belief,Yes,Other,Affirmative,True,NaN,NaN,NaN,"Noch vor wenigen Wochen wurden ""Verschwörungst...",noch vor wenigen wochen wurden verschwörungsth...,"noch vor wenigen wochen wurden "" verschwörungs...",telegram
1,16102,Yes,"Actor, Strategy, Goal, Reference",Belief,Yes,Other,Affirmative,NaN,NaN,NaN,NaN,BUNDESKANZLER UND BAUMEISTER YEHUDA TEICHTAL B...,bundeskanzler und baumeister yehuda teichtal b...,bundeskanzler und baumeister yehuda teichtal b...,telegram
2,15867,Uncertain,None,None,Yes,Post-Holocaust,Affirmative,True,NaN,NaN,NaN,"🔴 Impfstoff 'Holocaust' beginnt in Israel, als...",impfstoff holocaust beginnt in israel als der ...,"🔴 impfstoff ' holocaust ' beginnt in israel , ...",telegram
3,16314,No,None,None,No,None,None,NaN,NaN,NaN,NaN,Seit Marionette Biden im Amt ist zeigt die isr...,seit marionette biden im amt ist zeigt die isr...,seit marionette biden im amt ist zeigt die isr...,telegram
4,16313,No,None,None,No,None,None,True,NaN,NaN,NaN,In Israel sind nach Impfungen mit dem Mittel v...,in israel sind nach impfungen mit dem mittel v...,in israel sind nach impfungen mit dem mittel v...,telegram

## Store results

In [201]:
# data_clean.to_json('data_prepared/telegram_vs_twitter/telegram_all.json')

In [202]:
# data_clean.to_csv('data_prepared/telegram_vs_twitter/telegram_all.csv')