In [6]:
import Levenshtein as lev
import pandas as pd

from datetime import datetime

import itertools
from itertools import combinations

from random import sample

In [2]:
df = pd.read_csv('../temp/demotermine_cleaned_2022_06_20-2.csv', parse_dates=['date', 'edit_date'])

In [3]:
df.head()

,Unnamed: 0,channel_name,channel_id,channel_description,message_id,from_id,via_bot_id,date,edit_date,text,forwards,fwd_from,replies,reply_to,media,views,id,cleaned_text
0,0,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,15971,NaN,NaN,2021-08-29 11:11:25,2021-08-29 11:10:12,Berlin 29.08.2021 um 13 : 10 Uhr\nIn ungefähr ...,0.0,NaN,"MessageReplies(replies=0, replies_pts=290294, ...",NaN,NaN,1779.0,Demotermine1250288610159712021-08-29 11:10:12,Berlin 29.08.2021 um 13 : 10 Uhr In ungefähr 2...
1,2,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,23371,NaN,NaN,2021-10-26 09:58:45,2021-10-26 09:58:28,Vic Aus 🇦🇺 Dan Andrews caught bluffing again.....,1.0,NaN,"MessageReplies(replies=0, replies_pts=290292, ...",NaN,MessageMediaDocument(document=Document(id=6323...,1834.0,Demotermine1250288610233712021-10-26 09:58:28,Vic Aus 🇦 🇺 Dan Andrews caught bluffing again ...
2,3,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,10449,NaN,NaN,2021-05-13 06:52:14,2021-05-13 07:02:17,🌏 World Wide Demonstration 2.0 🌏\n\n\n💫 Ukrai...,2.0,NaN,"MessageReplies(replies=0, replies_pts=290300, ...",NaN,MessageMediaPhoto(photo=Photo(id=5239960968883...,2226.0,Demotermine1250288610104492021-05-13 07:02:17,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K..."
3,4,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,6885,NaN,NaN,2021-02-27 07:11:14,2021-02-27 07:11:32,🗓 27 Feb: Sternmarsch – Graz BEHÖRDLICH VERBOT...,1.0,NaN,"MessageReplies(replies=0, replies_pts=290300, ...",NaN,MessageMediaWebPage(webpage=WebPage(id=2944466...,4373.0,Demotermine125028861068852021-02-27 07:11:32,🗓 27 Feb : Sternmarsch – Graz BEHÖRDLICH VERBO...
4,5,Demotermine,1250288610,🔊 Wir Demokraten wollen miteinander in Kontakt...,22413,NaN,NaN,2021-10-20 04:49:20,2021-10-20 04:48:43,https://t.me/freiejugend\n\nRaus auf die Straß...,7.0,NaN,"MessageReplies(replies=0, replies_pts=290292, ...",NaN,MessageMediaPhoto(photo=Photo(id=5438483832002...,1203.0,Demotermine1250288610224132021-10-20 04:48:43,https://t.me/freiejugend Raus auf die Straßen ...

In [7]:
len(df)

27627

In [8]:
sample_size = 4000

In [9]:
df = df.sample(sample_size, random_state=42)

In [10]:
def get_combinations(arr, r):
    # return list of all subsets of length r
    # to deal with duplicate subsets use 
    return set(list(combinations(arr, r)))
    
    # else use return list(combinations(arr, r))

In [11]:
ts_before = datetime.now()
comb_dict = dict(zip(df.cleaned_text.values[:10000], df.message_id[:10000].values))
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")
###############

Took 0:00:00.019575

In [12]:
ts_before = datetime.now()
result_list = list(map(dict, itertools.combinations(
    comb_dict.items(), 2)))
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")
################

Took 0:00:01.682099

In [13]:
ts_before = datetime.now()
result = {}
index = 0  

for ele in result_list:
    result[index] = ele        
    index += 1 
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")
################

Took 0:00:02.161429

In [14]:
ts_before = datetime.now()
for k in result.keys():

    texts = list(result[k].keys())
    
    text_1 = texts[0]
    text_2 = texts[1]
    
    result[k]['lev_score'] = lev.ratio(text_1, text_2)
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")
#################

Took 0:00:52.041708

In [15]:
ts_before = datetime.now()
dict_to_df = {}

for key in result.keys():
    vals = result[key].values()    
    dict_to_df[key] = vals
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")
#################

Took 0:01:08.524182

In [ ]:
ts_before = datetime.now()
lev_df = pd.DataFrame.from_dict(dict_to_df).transpose().rename(columns={0: 'id_1', 1: 'id_2', 2: 'lev_score'})
lev_df = lev_df.astype({'id_1':'int', 'id_2':'int'}) 
ts_after = datetime.now()
print(f"Took {ts_after - ts_before}")

In [7]:
lev_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4950 entries, 0 to 4949
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_1       4950 non-null   int64
 1   id_2       4950 non-null   int64
 2   lev_score  4950 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 154.7 KB

In [147]:
treshold = 0.8

In [148]:
ids_to_drop = lev_df[lev_df['lev_score'] >= treshold].id_2.tolist()

In [149]:
len(ids_to_drop)

26

In [150]:
result_df = df[~df.message_id.isin(ids_to_drop)]

In [151]:
len(result_df)

27618

In [6]:
texts = df['cleaned_text'].values[:100]

In [7]:
text_combs = get_combinations(texts, 2)

In [8]:
msg_ids = df['message_id'].values[:100]

In [9]:
id_combs = get_combinations(df['message_id'].values[:100], 2)

In [10]:
len(id_combs)

4950

In [11]:
len(text_combs)

4950

In [27]:
zipped = list(zip(text_combs, id_combs))

In [28]:
len(zipped)

4950

In [29]:
pd.DataFrame(zipped)

                                                      0               1
0     (💚 💚 💚 Bitte kommt wieder zahlreich nach Poing...  (14617, 12299)
1     (Stuttgart-Stream von Stephan Bergmann u.a. mi...  (10453, 14929)
2     (🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 ...  (10790, 12299)
3     (Polizei dein Freund und Helfer Berlin Demo 29...   (4836, 17547)
4     (Das kommende Desaster : Rot-Rot-Grün mit Scho...  (15586, 28147)
...                                                 ...             ...
4945  (Vic Aus 🇦 🇺 Dan Andrews caught bluffing again...  (10248, 16325)
4946  (+ + + Potsdamer Platz : Polizei sagt mit symp...  (10783, 15437)
4947  (DIVINE - Alien's Best Friend - We are all div...  (23483, 10539)
4948  (+ + + Diesen Sonntag in Rothenburg + + + ❗ ️ ...   (5317, 10559)
4949  (🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , ...  (24799, 24859)

[4950 rows x 2 columns]

In [12]:
levs = []

for ele in text_combs:
    result = {}
    result['text_1'] = ele[0]
    result['text_2'] = ele[1]
    result['lev_score'] = lev.ratio(ele[0], ele[1])

    levs.append(result)

In [16]:
res = pd.DataFrame(levs)

In [17]:
res.head()

,text_1,text_2,lev_score
0,💢 💢 💢 💢 FREITAG 💢 💢 💢 💢 ‼️Es ist nicht genug z...,"Auch am heutigen Samstag , 10. Juli , meditier...",0.336093
1,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,Danke an alle Teilnehmer für den tollen Autoko...,0.317757
2,Raus auf die Straße @Demotermine!,+ + + Diesen Sonntag in Rothenburg + + + ❗ ️ ❗...,0.153488
3,Polizei dein Freund und Helfer Berlin Demo 29....,💥 💥 You are invited 💥 💥 World Wide Rally for F...,0.220134
4,💢 💢 💢 💢 FREITAG 💢 💢 💢 💢 ‼️Es ist nicht genug z...,🗓 INFOTISCH – Wien #Termin @OesterreichChat 29...,0.146915

In [18]:
len(res)

4950

In [19]:
res[res['lev_score'] >= 0.8]

,text_1,text_2,lev_score
137,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.842482
201,https://telesco.pe/info_direkt/2991 Raus auf d...,https://telesco.pe/info_direkt/2976 Raus auf d...,0.978947
250,"🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.843137
602,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.838253
689,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...",0.831962
747,"🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.848214
848,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,0.942113
943,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...",0.942895
984,"🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...","🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...",0.867558
1130,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...","🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...",0.917647
1259,"🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...","🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...",0.847337
1547,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...","🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...",0.877805
1579,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...",0.919897
1676,"🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...","🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...",0.897959
1690,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,0.862330
1825,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...,0.869432
2024,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...",0.875462
2342,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.848677
2449,https://t.me/freiejugend Raus auf die Straßen ...,https://telesco.pe/info_direkt/2991 Raus auf d...,0.837989
2465,"🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...","🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.908879
2533,https://t.me/freiejugend Raus auf die Straßen ...,https://telesco.pe/info_direkt/2976 Raus auf d...,0.837989
3287,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...",0.832569
3291,"🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...","🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.879121
3610,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...","🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...",0.866505
3745,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 France , Mu...",0.871287
3796,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...",0.846402
3895,"🌏 World Wide Demonstration 2.0 🌏 💫 Japan , Nag...","🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.884712
4019,"🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...","🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.902050
4069,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...","🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.864088
4081,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 Canada , Cr...",0.857143
4370,🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,"🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...",0.882280
4464,"🌏 World Wide Demonstration 2.0 🌏 💫 Virginia , ...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.842841
4704,"🌏 World Wide Demonstration 2.0 🌏 💫 Romania , B...","🌏 World Wide Demonstration 2.0 🌏 💫 Serbia , Be...",0.867713
4819,"🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...",🌏 World Wide Demonstration 2.0 🌏 💫 Lopez Islan...,0.827907

In [149]:
test.head(10)

   message_id                                       cleaned_text
0       15971  Berlin 29.08.2021 um 13 : 10 Uhr In ungefähr 2...
1       23371  Vic Aus 🇦 🇺 Dan Andrews caught bluffing again ...
2       10449  🌏 World Wide Demonstration 2.0 🌏 💫 Ukraine , K...
3        6885  🗓 27 Feb : Sternmarsch – Graz BEHÖRDLICH VERBO...
4       22413  https://t.me/freiejugend Raus auf die Straßen ...
5        4836  Stuttgart-Stream von Stephan Bergmann u.a. mit...
6        3105  Demo-Termine von https://terminkalender.top Zu...
7       10783  💢 💢 💢 💢 FREITAG 💢 💢 💢 💢 ‼️Es ist nicht genug z...
8       26583  🌏 WORLD WIDE DEMONSTRATION FOR FREEDOM 5.0 🌎 💫...
9        9261  ❗ ️Bitte teilen ❗ ️ Demo in Halle ( Saale ): F...

In [142]:
ids_to_drop = res[res['lev_score'] >= 0.8].id_2.tolist()

In [143]:
len(ids_to_drop)

0

In [144]:
result_df = df[~df.message_id.isin(ids_to_drop)]