## imports

In [2]:
import pandas as pd
from datasets import load_dataset

In [40]:
ds = load_dataset('smartdata')

Reusing dataset smartdata (/Users/elisabeth/.cache/huggingface/datasets/smartdata/smartdata-v3_20200302/1.1.0/9a495ae1310b73f664fa8644c7472f87ec728326e37fe67e030107712b81167f)

  0%|          | 0/3 [00:00<?, ?it/s]

In [41]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 1861
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 230
    })
    validation: Dataset({
        features: ['id', 'tokens', 'ner_tags'],
        num_rows: 228
    })
})

In [42]:
ds['train']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 1861
})

In [43]:
ds['test']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 230
})

In [44]:
ds['validation']

Dataset({
    features: ['id', 'tokens', 'ner_tags'],
    num_rows: 228
})

In [45]:
ds.column_names

{'train': ['id', 'tokens', 'ner_tags'],
 'test': ['id', 'tokens', 'ner_tags'],
 'validation': ['id', 'tokens', 'ner_tags']}

In [46]:
train_ds = ds['train']

In [47]:
features = train_ds.features

In [48]:
features['ner_tags']

Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)

In [49]:
ner_tags = train_ds.features['ner_tags']

In [50]:
ner_tags

Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)

In [51]:
# smartdata.set_format(type='pandas')

In [52]:
# df = smartdata['train'][:]

In [53]:
# df.head()

In [54]:
# def label_int2str(row):
  #  return smartdata['train'].features['ner_tags'].int2str(row)

In [55]:
# df['label_names'] = df['ner_tags'].apply(label_int2str)

In [56]:
for key, value in ds["train"].features.items():
    print(f"{key}: {value}")

id: Value(dtype='string', id=None)
tokens: Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)
ner_tags: Sequence(feature=ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None), length=-1, id=None)

In [57]:
tags = ds["train"].features["ner_tags"].feature
print(tags)

ClassLabel(num_classes=33, names=['O', 'B-DATE', 'I-DATE', 'B-DISASTER_TYPE', 'I-DISASTER_TYPE', 'B-DISTANCE', 'I-DISTANCE', 'B-DURATION', 'I-DURATION', 'B-LOCATION', 'I-LOCATION', 'B-LOCATION_CITY', 'I-LOCATION_CITY', 'B-LOCATION_ROUTE', 'I-LOCATION_ROUTE', 'B-LOCATION_STOP', 'I-LOCATION_STOP', 'B-LOCATION_STREET', 'I-LOCATION_STREET', 'B-NUMBER', 'I-NUMBER', 'B-ORGANIZATION', 'I-ORGANIZATION', 'B-ORGANIZATION_COMPANY', 'I-ORGANIZATION_COMPANY', 'B-ORG_POSITION', 'I-ORG_POSITION', 'B-PERSON', 'I-PERSON', 'B-TIME', 'I-TIME', 'B-TRIGGER', 'I-TRIGGER'], id=None)

In [58]:
def create_tag_names(batch):
    return {"ner_tags_str": [tags.int2str(idx) for idx in batch["ner_tags"]]}

In [59]:
ds = ds.map(create_tag_names)

  0%|          | 0/1861 [00:00<?, ?ex/s]

  0%|          | 0/230 [00:00<?, ?ex/s]

  0%|          | 0/228 [00:00<?, ?ex/s]

In [60]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 1861
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 230
    })
    validation: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'ner_tags_str'],
        num_rows: 228
    })
})

In [61]:
ds["train"][0]

{'id': '671734738147758080',
 'tokens': ['A1',
  'Zwischen',
  'AS',
  'Munsbach',
  'und',
  'AS',
  'Flaxweiler',
  'Bauarbeiten',
  ',',
  'rechter',
  'Fahrstreifen',
  'gesperrt',
  ',',
  'Verkehrsbehinderung',
  ',',
  'Dauer',
  ':',
  '02.12.2015',
  '...',
  '#ACL_A1'],
 'ner_tags': [17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 1, 0, 17],
 'ner_tags_str': ['B-LOCATION_STREET',
  'O',
  'B-LOCATION',
  'I-LOCATION',
  'O',
  'B-LOCATION',
  'I-LOCATION',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-TRIGGER',
  'O',
  'O',
  'O',
  'B-DATE',
  'O',
  'B-LOCATION_STREET']}

In [62]:
example = ds["train"][3]
pd.DataFrame([example["tokens"], example["ner_tags_str"]],
['Tokens', 'Tags']).transpose()

          Tokens               Tags
0       Vorsicht                  O
1          bitte                  O
2             in                  O
3         beiden         B-LOCATION
4     Richtungen         I-LOCATION
5            auf                  O
6            der                  O
7            A23  B-LOCATION_STREET
8          Heide    B-LOCATION_CITY
9              -                  O
10       Hamburg    B-LOCATION_CITY
11      zwischen                  O
12     Pinneberg         B-LOCATION
13             -         I-LOCATION
14          Nord         I-LOCATION
15           und                  O
16     Pinneberg         B-LOCATION
17             -         I-LOCATION
18         Mitte         I-LOCATION
19      befindet                  O
20          sich                  O
21          eine                  O
22  ungesicherte                  O
23  Unfallstelle          B-TRIGGER
24             !                  O

In [69]:
example = ds["train"][9]
pd.DataFrame([example["tokens"], example["ner_tags_str"]],
['Tokens', 'Tags']).transpose()

         Tokens             Tags
0   #Hochwasser  B-DISASTER_TYPE
1   #FAHRENHOLZ  B-LOCATION_CITY
2             -  I-LOCATION_CITY
3            UP  I-LOCATION_CITY
4             @                O
5      #ILMENAU       B-LOCATION
6           ---                O
7             >                O
8        #Pegel                O
9            in                O
10           58       B-DURATION
11          min       I-DURATION
12           um                O
13           16         B-NUMBER
14           cm         I-NUMBER
15          auf                O
16          764         B-NUMBER
17           cm         I-NUMBER
18    gestiegen                O
19            .                O
20            [                O
21        Stand                O
22            :                O
23        14:56           B-TIME
24            ]                O

In [63]:
# smartdata.set_format(type='pandas')

In [29]:
from collections import defaultdict

from collections import Counter

split2freqs = defaultdict(Counter)
for split, dataset in ds.items():
    for row in dataset["ner_tags_str"]:
        for tag in row:
            if tag.startswith("B"):
                tag_type = tag.split("-")[1]
                split2freqs[split][tag_type] += 1
pd.DataFrame.from_dict(split2freqs, orient="index")

,LOCATION_STREET,LOCATION,TRIGGER,DATE,LOCATION_CITY,TIME,ORGANIZATION_COMPANY,PERSON,NUMBER,ORGANIZATION,LOCATION_ROUTE,LOCATION_STOP,DURATION,DISASTER_TYPE,DISTANCE,ORG_POSITION
train,567,2249,1061,1511,1922,556,2384,978,1519,839,275,788,297,179,168,85
test,80,240,151,168,218,69,236,100,167,71,46,143,43,14,19,9
validation,64,298,127,167,252,69,311,127,156,76,37,74,49,31,17,12

In [33]:
# ds.set_format(type='pandas')

In [34]:
# df = ds['train'][:]

In [37]:
# df.head()

,id,tokens,ner_tags,ner_tags_str
0,671734738147758080,"[A1, Zwischen, AS, Munsbach, und, AS, Flaxweil...","[17, 0, 9, 10, 0, 9, 10, 0, 0, 0, 0, 0, 0, 31,...","[B-LOCATION_STREET, O, B-LOCATION, I-LOCATION,..."
1,744611433661472768,"[RT, @broeselbub, :, Wer, diesen, #EM16, -, Sp...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,http://www.viz-info.de/LMS-BR_r_LMS-BR_63500@2...,"[Sonstiges, Abschnitt, :, (, Berlin, ), Gültig...","[0, 0, 0, 0, 11, 0, 0, 0, 0, 1, 29, 0, 0, 0, 0...","[O, O, O, O, B-LOCATION_CITY, O, O, O, O, B-DA..."
3,http://www.ndr.de/nachrichten/verkehr/index.ht...,"[Vorsicht, bitte, in, beiden, Richtungen, auf,...","[0, 0, 0, 9, 10, 0, 0, 17, 11, 0, 11, 0, 9, 10...","[O, O, O, B-LOCATION, I-LOCATION, O, O, B-LOCA..."
4,699639035099279361,"[RT, @BILD, :, Wegen, Schulden, :, Rapper, #Ka...","[0, 23, 0, 0, 0, 0, 0, 27, 0, 23, 0, 0, 27, 28...","[O, B-ORGANIZATION_COMPANY, O, O, O, O, O, B-P..."