In [19]:
import pandas as pd
import re
import ast

In [2]:
df = pd.read_csv('test.csv')

In [3]:
df.head()

,Unnamed: 0,Unnamed: 0.1,id,message_id,date,cleaned_text,lang,text_length,label,annotator,annotation_id,created_at,updated_at,lead_time
0,839,1393,26230,32022,2021-12-17 00:34:40,Montagsspaziergang in # Schutterwald . 18.00 U...,de,116,"[{""start"": 0, ""end"": 18, ""text"": ""Montagsspazi...",6,5819,2022-06-20T15:34:50.470891Z,2022-06-20T15:34:50.470929Z,29.512
1,11081,22733,26229,27145,2021-11-19 16:09:46,Bitte teilenKommt alle nach Halle Demonstratio...,de,664,"[{""start"": 28, ""end"": 33, ""text"": ""Halle"", ""la...",6,5818,2022-06-20T15:34:20.489139Z,2022-06-20T15:34:20.489165Z,93.281
2,4867,8985,26228,15055,2021-08-27 18:05:57,! ! Ahrtal | Das erste offizielle Video ist fe...,de,182,"[{""start"": 4, ""end"": 10, ""text"": ""Ahrtal"", ""la...",6,5817,2022-06-20T15:32:46.802643Z,2022-06-20T15:32:46.802682Z,15.095
3,10090,20431,26227,2266,2020-08-03 12:28:14,Mutprobe Demo 3. August 2020 Plüderhausen Fest...,de,317,"[{""start"": 29, ""end"": 41, ""text"": ""Plüderhause...",6,5816,2022-06-20T15:32:31.301636Z,2022-06-20T15:32:31.301668Z,62.296
4,9338,18560,26226,4658,2020-12-21 03:31:32,"Es wird immer mehr beobachtet , wie die Polize...",de,105,"[{""start"": 52, ""end"": 58, ""text"": ""Antifa"", ""l...",6,5815,2022-06-20T15:31:28.572282Z,2022-06-20T15:31:28.572313Z,10.674

In [21]:
annos = (df.iloc[1].label)

In [22]:
res = annos.replace('[', '').replace(']','')

In [23]:
res

'{"start": 28, "end": 33, "text": "Halle", "labels": "LOC"}, {"start": 70, "end": 85, "text": "Halle ( Saale )", "labels": "LOC"}, {"start": 99, "end": 111, "text": "Riebeckplatz", "labels": "LOC"}, {"start": 238, "end": 254, "text": "Halle ( Saale ) ", "labels": "LOC"}, {"start": 314, "end": 326, "text": "Riebeckplatz", "labels": "LOC"}, {"start": 334, "end": 346, "text": "Hauptbahnhof", "labels": "LOC"}, {"start": 389, "end": 401, "text": "Riebeckplatz", "labels": "LOC"}, {"start": 405, "end": 410, "text": "Halle", "labels": "LOC"}, {"start": 623, "end": 625, "text": "ST", "labels": "LOC"}, {"start": 637, "end": 642, "text": "Halle", "labels": "LOC"}, {"start": 116, "end": 125, "text": "Sonnabend", "labels": "DATE"}, {"start": 132, "end": 142, "text": "27.11.2021", "labels": "DATE"}, {"start": 628, "end": 634, "text": "Sa2711", "labels": "DATE"}, {"start": 161, "end": 170, "text": "18.00 Uhr", "labels": "TIME"}, {"start": 147, "end": 156, "text": "16:00 Uhr", "labels": "TIME"}, {"start": 34, "end": 47, "text": "Demonstration", "labels": "EVENT"}, {"start": 52, "end": 63, "text": "Spaziergang", "labels": "EVENT"}, {"start": 260, "end": 265, "text": "Umzug", "labels": "EVENT"}, {"start": 367, "end": 380, "text": "Demonstration", "labels": "EVENT"}'

In [24]:
ast.literal_eval(res)

({'start': 28, 'end': 33, 'text': 'Halle', 'labels': 'LOC'},
 {'start': 70, 'end': 85, 'text': 'Halle ( Saale )', 'labels': 'LOC'},
 {'start': 99, 'end': 111, 'text': 'Riebeckplatz', 'labels': 'LOC'},
 {'start': 238, 'end': 254, 'text': 'Halle ( Saale ) ', 'labels': 'LOC'},
 {'start': 314, 'end': 326, 'text': 'Riebeckplatz', 'labels': 'LOC'},
 {'start': 334, 'end': 346, 'text': 'Hauptbahnhof', 'labels': 'LOC'},
 {'start': 389, 'end': 401, 'text': 'Riebeckplatz', 'labels': 'LOC'},
 {'start': 405, 'end': 410, 'text': 'Halle', 'labels': 'LOC'},
 {'start': 623, 'end': 625, 'text': 'ST', 'labels': 'LOC'},
 {'start': 637, 'end': 642, 'text': 'Halle', 'labels': 'LOC'},
 {'start': 116, 'end': 125, 'text': 'Sonnabend', 'labels': 'DATE'},
 {'start': 132, 'end': 142, 'text': '27.11.2021', 'labels': 'DATE'},
 {'start': 628, 'end': 634, 'text': 'Sa2711', 'labels': 'DATE'},
 {'start': 161, 'end': 170, 'text': '18.00 Uhr', 'labels': 'TIME'},
 {'start': 147, 'end': 156, 'text': '16:00 Uhr', 'labels': 'TIME'},
 {'start': 34, 'end': 47, 'text': 'Demonstration', 'labels': 'EVENT'},
 {'start': 52, 'end': 63, 'text': 'Spaziergang', 'labels': 'EVENT'},
 {'start': 260, 'end': 265, 'text': 'Umzug', 'labels': 'EVENT'},
 {'start': 367, 'end': 380, 'text': 'Demonstration', 'labels': 'EVENT'})

In [15]:
text = df.iloc[0].cleaned_text

In [26]:
annos

'[{"start": 0, "end": 18, "text": "Montagsspaziergang", "labels": ["EVENT"]}, {"start": 24, "end": 36, "text": "Schutterwald", "labels": ["LOC"]}, {"start": 52, "end": 59, "text": "Rathaus", "labels": ["LOC"]}, {"start": 64, "end": 66, "text": "BW", "labels": ["LOC"]}, {"start": 69, "end": 75, "text": "Mo2012", "labels": ["DATE"]}, {"start": 78, "end": 84, "text": "Mo2712", "labels": ["DATE"]}, {"start": 39, "end": 48, "text": "18.00 Uhr", "labels": ["TIME"]}]'

In [25]:
df = pd.read_json('test.json')

In [26]:
df.head()

,id,annotations,file_upload,drafts,predictions,data,meta,created_at,updated_at,inner_id,total_annotations,cancelled_annotations,total_predictions,project,updated_by
0,26230,"[{'id': 5819, 'completed_by': 6, 'result': [{'...",b43e28ff-sample_data_2022_06_20.csv,[],[],"{'Unnamed: 0': 839, 'Unnamed: 0.1': 1393, 'id'...",{},2022-06-20 12:57:36.696897+00:00,2022-06-20 15:34:50.524389+00:00,116,1,0,0,48,6
1,26229,"[{'id': 5818, 'completed_by': 6, 'result': [{'...",b43e28ff-sample_data_2022_06_20.csv,[],[],"{'Unnamed: 0': 11081, 'Unnamed: 0.1': 22733, '...",{},2022-06-20 12:57:36.696840+00:00,2022-06-20 15:34:20.549349+00:00,115,1,0,0,48,6
2,26228,"[{'id': 5817, 'completed_by': 6, 'result': [{'...",b43e28ff-sample_data_2022_06_20.csv,[],[],"{'Unnamed: 0': 4867, 'Unnamed: 0.1': 8985, 'id...",{},2022-06-20 12:57:36.696792+00:00,2022-06-20 15:32:46.859639+00:00,114,1,0,0,48,6
3,26227,"[{'id': 5816, 'completed_by': 6, 'result': [{'...",b43e28ff-sample_data_2022_06_20.csv,[],[],"{'Unnamed: 0': 10090, 'Unnamed: 0.1': 20431, '...",{},2022-06-20 12:57:36.696736+00:00,2022-06-20 15:32:31.351609+00:00,113,1,0,0,48,6
4,26226,"[{'id': 5815, 'completed_by': 6, 'result': [{'...",b43e28ff-sample_data_2022_06_20.csv,[],[],"{'Unnamed: 0': 9338, 'Unnamed: 0.1': 18560, 'i...",{},2022-06-20 12:57:36.696690+00:00,2022-06-20 15:31:28.628817+00:00,112,1,0,0,48,6

In [41]:
df.annotations[0][0]['result']

[{'value': {'start': 0,
   'end': 18,
   'text': 'Montagsspaziergang',
   'labels': ['EVENT']},
  'id': '7AqlH7bvaC',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 24, 'end': 36, 'text': 'Schutterwald', 'labels': ['LOC']},
  'id': '8GZN11GZ4-',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 52, 'end': 59, 'text': 'Rathaus', 'labels': ['LOC']},
  'id': 'xiZiVqg5Bb',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 64, 'end': 66, 'text': 'BW', 'labels': ['LOC']},
  'id': 'BUKodt1LP1',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 69, 'end': 75, 'text': 'Mo2012', 'labels': ['DATE']},
  'id': 'qSQ13Vq4xH',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 78, 'end': 84, 'text': 'Mo2712', 'labels': ['DATE']},
  'id': 'VTwyDyNH5q',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'},
 {'value': {'start': 39, 'end': 48, 'text': '18.00 Uhr', 'labels': ['TIME']},
  'id': 'Lujnmi-7aJ',
  'from_name': 'label',
  'to_name': 'text',
  'type': 'labels',
  'origin': 'manual'}]

In [47]:
df.data[0]['cleaned_text']

'Montagsspaziergang in # Schutterwald . 18.00 Uhr am Rathaus . # BW # Mo2012 # Mo2712 # montags Übersicht / Overview'